import {
  ActionIcon,
  Badge,
  Button,
  Card,
  Grid,
  Group,
  Input,
  Modal,
  RingProgress,
  Select,
  Text,
  TextInput,
} from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import { RichTextEditor } from "@mantine/tiptap";
import { useEditor } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import { DatePickerInput } from "@mantine/dates";
import {
  Dropzone,
  IMAGE_MIME_TYPE,
  type DropzoneProps,
} from "@mantine/dropzone";
import {
  CloudUpload,
  Diamond,
  MoreVertical,
  Search,
} from "lucide-react";
import { useState } from "react";
import { EPIC_LISTS, STORY_LISTS } from "../../../utils/helper/project.helper";

export const EpicPage = (props: Partial<DropzoneProps>) => {
  const [opened, { open, close }] = useDisclosure(false);
  const [openedStory, { open: openStory, close: closeStory }] =
    useDisclosure(false);
  const [value, setValue] = useState<string | null>(null);

  const editor = useEditor({
    extensions: [StarterKit],
    content: "<p>Enter Story Description...</p>",
  });

  const editors = useEditor({
    extensions: [StarterKit],
    content: "<p>Enter Story Description...</p>",
  });

  const TaskRow = ({ task }: { task: any }) => (
    <tr className="border-b border-gray-100 hover:bg-gray-50">
      <td className="p-4 w-32">
        <Text c="blue" fw={600} size="sm">
          {task.id}
        </Text>
      </td>
      <td className="p-4 flex-1">
        <Text size="sm" fw={500}>
          {task.title}
        </Text>
      </td>
      <td className="p-4 w-32">
        <Group gap="xs">
          <Badge variant="light" color="blue" size="sm">
            {task.status}
          </Badge>
        </Group>
      </td>
      <td className="p-4 w-24">
        <Group gap="xs">
          <ActionIcon size="sm" variant="subtle">
            <Diamond size={12} className="text-orange-500 fill-orange-500" />
          </ActionIcon>
          <ActionIcon size="sm" variant="subtle">
            <Diamond size={12} className="text-yellow-500 fill-yellow-500" />
          </ActionIcon>
        </Group>
      </td>
      <td className="p-4 w-24">
        <ActionIcon variant="subtle" color="rgba(0, 0, 0, 1)">
          <MoreVertical size={18} />
        </ActionIcon>
      </td>
    </tr>
  );

  const ProjectCard = ({ project }: { project: any }) => (
    <Card
      withBorder
      radius="lg"
      shadow="sm"
      padding="lg"
      className="w-95 h-20 mt-lg"
    >
      <Group justify="space-between" align="flex-start">
        <div className="flex gap-2">
          <RingProgress
            size={50}
            thickness={5}
            sections={[{ value: project.progress, color: "blue" }]}
            label={
              <Text c="blue" fw={200} ta="center" size="xs">
                {project.progress}%
              </Text>
            }
          />
          <div className="flex flex-col gap-1">
            <Text fw={500}>
              {project.id} {project.title}
            </Text>
            <Text size="xs">Generated By: {project.assignee}</Text>
          </div>
        </div>
        <ActionIcon variant="subtle" color="rgba(0, 0, 0, 1)">
          <MoreVertical size={18} />
        </ActionIcon>
      </Group>
    </Card>
  );

  return (
    <>
      <Grid>
        <Grid.Col span={3}>
          <Group justify="space-between">
            <Text c="blue">Active</Text>
            <Button variant="filled" color="blue" onClick={open}>
              Create Epic
            </Button>
          </Group>
          <div className="flex flex-col gap-2">
            {EPIC_LISTS.map((v1) => (
              <ProjectCard key={v1.id} project={v1} />
            ))}
          </div>
        </Grid.Col>
        <Grid.Col span={9}>
          <div className="flex justify-between items-center">
            <Input
              placeholder="Search"
              className="w-60"
              variant="filled"
              leftSection={<Search size={20} />}
            />
            <Button variant="filled" color="blue" onClick={openStory}>
              Create Story
            </Button>
          </div>

          <div className="flex flex-col gap-2 mt-7 mb-4">
            <Text>User Authentication</Text>
            <Text size="md" ml={10}>
              Epic for user authentication
            </Text>
          </div>
          <div className="bg-white rounded-lg border border-gray-200">
            <div className="overflow-x-auto">
              <table className="w-full">
                <tbody>
                  {STORY_LISTS.map((v) => (
                    <TaskRow key={v.id} task={v} />
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </Grid.Col>
        <Modal opened={opened} onClose={close} title="Create Epic" size="md">
          <div className="flex flex-col gap-4">
            <TextInput
              label="Name"
              variant="filled"
              withAsterisk
              placeholder="Enter Project Name"
            />
            <div>
              <Text size="sm" fw={500}>
                Description <span style={{ color: "red" }}>*</span>
              </Text>
              <RichTextEditor editor={editor} variant="subtle" className="h-80">
                <RichTextEditor.Toolbar
                  sticky
                  stickyOffset="var(--docs-header-height)"
                >
                  <RichTextEditor.ControlsGroup>
                    <RichTextEditor.Bold />
                    <RichTextEditor.Italic />
                    <RichTextEditor.Underline />
                    <RichTextEditor.Strikethrough />
                    <RichTextEditor.ClearFormatting />
                    <RichTextEditor.Highlight />
                    <RichTextEditor.Code />
                  </RichTextEditor.ControlsGroup>
                </RichTextEditor.Toolbar>

                <RichTextEditor.Content />
              </RichTextEditor>
            </div>
            <Select
              label="Board Type"
              variant="filled"
              placeholder="Select Board Type"
              withAsterisk
              data={["Kanban", "Scrum"]}
            />
          </div>
          <Group justify="flex-end" mt="xl">
            <Button variant="outline" color="blue">
              Cancel
            </Button>
            <Button variant="filled" color="blue">
              Create Epic
            </Button>
          </Group>
        </Modal>
        <Modal
          opened={openedStory}
          onClose={closeStory}
          title="Create Story"
          size={900}
        >
          <Grid>
            <Grid.Col span={8}>
              <div className="flex flex-col gap-4">
                <TextInput
                  label="Name"
                  variant="filled"
                  withAsterisk
                  placeholder="Enter Project Name"
                />
                <div>
                  <Text size="sm" fw={500}>
                    Description <span style={{ color: "red" }}>*</span>
                  </Text>
                  <RichTextEditor
                    editor={editors}
                    variant="subtle"
                    className="h-60"
                  >
                    <RichTextEditor.Toolbar
                      sticky
                      stickyOffset="var(--docs-header-height)"
                    >
                      <RichTextEditor.ControlsGroup>
                        <RichTextEditor.Bold />
                        <RichTextEditor.Italic />
                        <RichTextEditor.Underline />
                        <RichTextEditor.Strikethrough />
                        <RichTextEditor.ClearFormatting />
                        <RichTextEditor.Highlight />
                        <RichTextEditor.Code />
                      </RichTextEditor.ControlsGroup>
                    </RichTextEditor.Toolbar>

                    <RichTextEditor.Content />
                  </RichTextEditor>
                </div>
                <div>
                  <Text size="sm" fw={500}>
                    Acceptance Criteria <span style={{ color: "red" }}>*</span>
                  </Text>
                  <RichTextEditor
                    editor={editors}
                    variant="subtle"
                    className="h-60"
                  >
                    <RichTextEditor.Toolbar
                      sticky
                      stickyOffset="var(--docs-header-height)"
                    >
                      <RichTextEditor.ControlsGroup>
                        <RichTextEditor.Bold />
                        <RichTextEditor.Italic />
                        <RichTextEditor.Underline />
                        <RichTextEditor.Strikethrough />
                        <RichTextEditor.ClearFormatting />
                        <RichTextEditor.Highlight />
                        <RichTextEditor.Code />
                      </RichTextEditor.ControlsGroup>
                    </RichTextEditor.Toolbar>

                    <RichTextEditor.Content />
                  </RichTextEditor>
                </div>
              </div>
            </Grid.Col>
            <Grid.Col span={4}>
              <div className="flex flex-col gap-6">
                <TextInput
                  label="Estimated Size"
                  variant="filled"
                  withAsterisk
                  placeholder="Enter Estimated Size"
                />
                <Select
                  label="Priority"
                  variant="filled"
                  placeholder="Select Priority"
                  withAsterisk
                  data={["High", "Medium", "Low"]}
                />
                <Select
                  label="Status"
                  variant="filled"
                  placeholder="Select Status"
                  withAsterisk
                  data={["To Do", "In Progress", "Done"]}
                />
                <Select
                  label="Story Type"
                  variant="filled"
                  placeholder="Select Story Type"
                  withAsterisk
                  data={["Bug", "Feature", "Task"]}
                />
                <DatePickerInput
                  label="Pick date"
                  placeholder="Pick date"
                  variant="filled"
                  value={value}
                  onChange={setValue}
                />
                <Select
                  label="Assign to"
                  variant="filled"
                  placeholder="Select Assignee"
                  withAsterisk
                  data={["Kanban", "Scrum"]}
                />
                <Select
                  label="Report To"
                  variant="filled"
                  placeholder="Select Report To"
                  withAsterisk
                  data={["Kanban", "Scrum"]}
                />
                <Dropzone
                  onDrop={(files) => console.log("accepted files", files)}
                  onReject={(files) => console.log("rejected files", files)}
                  maxSize={5 * 1024 ** 2}
                  accept={IMAGE_MIME_TYPE}
                  {...props}
                >
                  {/* <Group gap="xl" mih={80} style={{ pointerEvents: 'none' }}> */}
                  <div className="min-h-20 flex items-center gap-4">
                    <CloudUpload size={80} />
                    <Text size="sm" c="dimmed" inline mt={7}>
                      Drop files to attach or Browse Files Supported files: PDF,
                      DOCX, PPT, XLSX, JPG, JPEG, PNG, GIF, WEBP, MP4
                    </Text>
                  </div>
                  {/* </Group> */}
                </Dropzone>
              </div>
            </Grid.Col>
          </Grid>

          <Group justify="flex-end" mt="xl">
            <Button variant="outline" color="blue">
              Cancel
            </Button>
            <Button variant="filled" color="blue">
              Create Story
            </Button>
          </Group>
        </Modal>
      </Grid>
    </>
  );
};
